// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyC5CtNfv7hQpUdBqVk1NpCa4ohMGPkrcEs",
      authDomain: "canteen-vjti.firebaseapp.com",
      projectId: "canteen-vjti",
      storageBucket: "canteen-vjti.appspot.com",
      messagingSenderId: "669007152872",
      appId: "1:669007152872:web:b8a4077bf5a868013a6b5d");

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyC5CtNfv7hQpUdBqVk1NpCa4ohMGPkrcEs",
      projectId: "canteen-vjti",
      storageBucket: "canteen-vjti.appspot.com",
      messagingSenderId: "669007152872",
      appId: "1:669007152872:web:b8a4077bf5a868013a6b5d");
}
